# Resumo {#resumo}

A literatura  na área da saúde aponta, em geral, que o desenvolvimento infantil é fruto da interação entre o sujeito consigo mesmo e com o ambiente ao seu redor.

O estudo analisado neste relatório estatístico busca identificar se os movimentos de apertar em bebês de até três meses de idade alteram-se ao longo de três sessões de prática nas diversas situações experimentais definidas pela pesquisadora. A partir desse objetivo, foram construídos testes não paramétricos a fim de entender se há diferença na frequência de apertos dos participantes em cada um dos cenários observados.
Eram esperados diferentes padrões de apertar em cada condição experimental e que este padrão se modificasse com o aumento da idade dos participantes. Ademais,também era desejado que os movimentos apresentassem diferenças do primeiro para o terceiro dia de participação no experimento, caracterizando uma crescente automonia dos bebês no controle das mãos com o aumento da idade.

Concluiu-se que, de modo geral, a heterogeneidade entre os bebês de um mesmo grupo dificulta notar padrões dentro e entre as faixas etárias. Além disso, a taxa de apertos por minuto de cada bebê em cada condição e dia não parece ser constante, o que pode indicar uma mudança de comportamento ao longo do tempo de sessão por parte dos participantes do estudo. Por fim, especificamente na condição basal 2, há indícios de que a mediana da frequência de apertos da primeira sessão é maior do que no segundo e terceiro dia de experimento.

