# Introdução {#introducao}

O estudo da ação manipulativa em bebês é uma forma de entender o desenvolvimento humano durante os primeiros meses de vida. Esse processo está relacionado ao descobrimento do próprio corpo pelo sujeito, bem como à influência do ambiente ao seu redor.
De acordo com a Fundação Oswaldo Cruz (Fiocruz, 2019)
“ O desenvolvimento infantil e a plasticidade cerebral são maiores nos primeiros anos de vida. Sendo assim, quaisquer perturbações no ambiente ou no indivíduo impactam substancialmente na aquisição das habilidades motoras e cognitivas”.
Portanto, um projeto descrito no presente relatório conjuntamente com as análises que serão realizados contribuem na caracterização do desenvolvimento infantil, auxiliando no processo de entender novas formas de estimular o potencial ativo dos recém-nascidos em seus primeiros meses de vida.
Salienta-se que o estudo tem como premissa a definição de que o comportamento de bebês ao nascer é ativo (voluntário) e não reflexo (involuntário). Conforme apontado pelas estudiosas (Haywood;Getchell, 2004), os reflexos representam apenas uma pequena parte do comportamento motor inicial dos indivíduos. Além disso, a literatura também aponta (Kawai, Savelsbergh, Wimmers, 1999) que os movimentos expontâneos (voluntários) parecem ser influenciados por restrições ambientais.
De modo geral, o intuito do trabalho é investigar a emergência e desenvolvimento do comportamento voluntário das mãos em bebês de até três meses de idade, com base em alguns cenários experimentais.
