# Descrição do estudo {#descricao-estudo}

## Participantes

O estudo foi realizado de maneira presencial em três sessões individuais, dentro de um período de 7 dias, entre a pesquisadora e cada um dos participantes. Consistiu em apresentar aos bebês quatro condições experimentais e registrar, para cada uma, dados de pressão palmar relacionados aos apertos que os bebês realizaram sobre um equipamento com sensor de pressão colocado na palma de suas mãos. 
A coleta dos dados foi realizada em 2018 com 22 indivíduos recrutados pelos pesquisadores através de conhecidos e da divulgação em redes sociais. Os voluntários tiveram como pré-requisitos nascimento entre 38 a 42 semanas de gestação (9 meses) sem nenhuma complicação médica no parto, ser considerado saúdavel por seus médicos de acompanhamento e estar na faixa etária de 1 a 3 meses de vida. 


##	Condições Experimentais

Os bebês foram colocados sentados em uma cadeira em frente a um monitor, em uma posição estável. Logo após, um sensor de pressão foi posicionado na mão do bebê, para captar os apertos durante o experimento. Em um período de, aproximadamente, 12 minutos foram apresentadas a cada um dos participantes quatro condições experimentais diferentes. Durante cada condição eram coletados as informações de pressão palmar exercidas por segundo pelos bebês.
Primeiramente, a pesquisadora apresentava a Condição Basal (sem nenhuma variação ambiental), na qual não era apresentado aos bebês nenhum estímulo visual. Em seguida, apresentavam em ordem aleatória duas outras condições: Contingente, na qual um vídeo aparecia se o sujeito atingisse determinada pressão palmar, e Não Contingente, na qual um vídeo aparecia de forma automâtica sem que o bebê atingisse o valor de pressão estipulado. Posteriormente, foi concedida uma segunda Condição Basal (Basal 2) para finalização da coleta. 
Em resumo, cada bebê realizou três sessões de testes compostas destas quatro condições dentro de um período de 7 dias e o vídeo aparecia de maneira Contingente (como consequência do aperto), Não Contingente (automaticamente programado) ou ainda Basal (sem o vídeo).


## Detalhamento do estímulo visual

Na condição Contingente, o valor utilizado como gatilho para o disparo do vídeo correspondia à pressão exercida pelo bebê durante 70% do tempo de coleta na tentativa Basal. Ou seja, o número varia de criança para criança e se altera em cada dia. Caso o participante não tenha atingido a frequência de 70% em algum dos dias do experimento, foi estipulado a pressão gatilho de 0,2 mmHg.
Já na condição Não Contingente, o vídeo era apresentado independente da pressão dos apertos realizados pelo sujeito.
Destacamos que o mesmo vídeo foi utilizado com todos os participantes do estudo.

## Limitações do estudo

Identificamos dois eventuais problemas -um de caráter técnico e outro de aleatorização- na coleta de dados que tentaremos contornar nas análises. Ambos são descritos a seguir.

Problemas técnicos e de caráter comportamental

Houve a interrupção de alguns processos de coleta de dados por causa da condição comportamental dos participantes. O estado de alerta do bebê durante o procedimento pode ser um fator que influência sua responsividade a estímulos e o cenário "perfeito" para a execução do teste seria quando o indivíduo estivesse quieto e acordado.
Em consequência desse fator, destaca-se que alguns bebês não possuem dados de pressão para todas condições em determinado dia. Após a coleta de dados, a pesquisadora também realizou cortes no tempo de observação de alguns participantes, devido a valores outliers relacionados a esses momentos de estresse da criança.
Além disso, há o número pequeno de participantes no estudo que dificulta  modelagens mais robustas. 

Problemas de aleatorização

Outro ponto de atenção foi o processo de aleatorização das condições Contingente e Não Contigente. Como a ordem de apresentação de ambas não é a mesma para os bebês isso pode comprometer a caracterização de um padrão no comportamento de apertar.

