---
title: "Dúvidas"
author: "Renata Hirota"
date: "8/26/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Arquivos

- Icon_
- não usar
- contexto (sonolento, chorando, ruído, etc)
- cortado, cortar depois, etc

# Pressão gatilho


Gatilho: pressão mais frequente (70% da tentativa) 0.2 caso contrário
- Gatilho muda a cada sessão? sim
- Como é estabelecido o limite a partir do basal?
- duração em qual unidade? minuto?

Para cada condição definida, foram coletados os valores de pressão palmar realizada pelos participante ao longo do tempo em cada dia do experimento. A partir deles, a pesquisadora identificou os picos de pressão ao
longo da série temporal que foram classificados como apertos. (é isso?)

# Variáveis sav

- somas de pressão milissegundos
- tentativa completa: tempo completo
- definição de pico de pressao e aperto. 
  - picos de pressão
  - aperto: a partir de determinada % de pressão 

## Janelada

- n de apertos não é acumulado
- @1m_c_30_abaixo_d1 = 4.886: tempo que ficou abaixo de 30%? ou pressão?
- acima de 30% e acima de 20% são disjuntos?

## Vídeo

- para todos os dias?
- Contingente: o video aparecia quando a pressão do bebe atingia 75% da pressão média na condição brasal? Ou era o valor de pressão exercida pelo
bebê no cilindro durante 75% do tempo de coleta na condição basal (desconsiderando os valores zero quando o bebe não fazia pressão no equipamento.)

## Experimento
- existem pré-requsitos e validação dos resultados?
- houve interrupções nas coletas por causa da condição dos bebes?
- condição experimental do bebe (acredito que isso influencia sua resposta a estimulos)
- quando foi realizada a coleta de dados
- os voluntarios tiveram algum pre requsito p participar? alem da idade
- pq existe uma segunda condição basal?

